development:
  adapter: postgresql
  encoding: unicode
  database: jlc_invest_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: jlc_invest_test
  pool: 5
  host: localhost
